
export const JEE_CHAPTERS = {
  Physics: [
    "Units and Dimensions",
    "Errors and Measurements",
    "Kinematics",
    "Laws of Motion",
    "Work, Energy and Power",
    "Circular Motion",
    "Centre of Mass",
    "Rotational Motion",
    "Gravitation",
    "Mechanical Properties of Solids",
    "Mechanical Properties of Fluids",
    "Simple Harmonic Motion",
    "Waves",
    "Thermal Properties of Matter",
    "Calorimetry",
    "Kinetic Theory of Gases",
    "Thermodynamics",
    "Heat Transfer",
    "Electrostatics",
    "Capacitors",
    "Current Electricity",
    "Moving Charges and Magnetism",
    "Magnetism and Matter",
    "Electromagnetic Induction",
    "Alternating Current",
    "Ray Optics",
    "Wave Optics",
    "Dual Nature of Matter",
    "Atoms",
    "Nuclei",
    "Semiconductor Electronics",
    "EM Waves"
  ],
  Chemistry: [
    "Some Basic Concepts of Chemistry",
    "Structure of Atom",
    "Classification of Elements and Periodicity in Properties",
    "Chemical Bonding and Molecular Structure",
    "States of Matter",
    "Thermodynamics",
    "Equilibrium",
    "Redox Reactions",
    "Hydrogen",
    "The s-Block Elements",
    "The p-Block Elements",
    "Organic Chemistry - Some Basic Principles and Techniques",
    "Hydrocarbons",
    "Environmental Chemistry",
    "Solid State",
    "Solutions",
    "Electrochemistry",
    "Chemical Kinetics",
    "Surface Chemistry",
    "General Principles and Processes of Isolation of Elements",
    "The d and f Block Elements",
    "Coordination Compounds",
    "Haloalkanes and Haloarenes",
    "Alcohols, Phenols and Ethers",
    "Aldehydes, Ketones and Carboxylic Acids",
    "Organic Compounds Containing Nitrogen",
    "Biomolecules",
    "Polymers",
    "Chemistry in Everyday Life"
  ],
  Maths: [
    "Sets, Relations and Functions",
    "Complex Numbers and Quadratic Equations",
    "Matrices and Determinants",
    "Permutations and Combinations",
    "Mathematical Induction",
    "Binomial Theorem and its Simple Applications",
    "Sequences and Series",
    "Limit, Continuity and Differentiability",
    "Integral Calculus",
    "Differential Equations",
    "Coordinate Geometry",
    "Three Dimensional Geometry",
    "Vector Algebra",
    "Statistics and Probability",
    "Trigonometry",
    "Mathematical Reasoning"
  ]
};
